
# Configurações de build
[build]
  publish = "dist"
  command = "npm run build"

# Redirecionamentos para Single-Page Application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cabeçalhos de segurança e cache
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.gpteng.co https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; connect-src 'self' https://*.supabase.co https://www.google-analytics.com; frame-src 'self'; upgrade-insecure-requests;"

# Configurações de cache para fontes
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configurações de cache para arquivos estáticos
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configurações de cache para imagens
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Configurações de cache para ícones e imagens
[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Configurações de cache para arquivos JavaScript, CSS e fontes
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
