
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkmqdjkhjtmlkbvuosbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rbXFkamtoanRtbGtidnVvc2J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NTcxNTEsImV4cCI6MjA2MTUzMzE1MX0.EycJ1vhmig1Zs_VHRlQnPip8SV3Jrii3JfCixBJ2PzU";

// A função getAuthOptions é usada para definir as configurações com base no "Lembrar de mim"
const getAuthOptions = () => {
  const rememberMe = localStorage.getItem('rememberMe') === 'true';
  
  return {
    auth: {
      persistSession: rememberMe,
      autoRefreshToken: rememberMe
    }
  };
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  getAuthOptions()
);

// Função para atualizar as configurações de autenticação
export const updateAuthSettings = (rememberMe: boolean) => {
  localStorage.setItem('rememberMe', String(rememberMe));
  // Observação: Como não podemos reconstruir o cliente, apenas atualizamos o localStorage
  // As novas configurações serão aplicadas na próxima vez que o cliente for criado (próxima sessão)
};
